services:
  homepagesite:
    container_name: homepagesite
    image: ghcr.io/robertkeres/homepagesite:1.0.1
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes:
      - ./data:/data
networks: {}
